In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
ipl = pd.read_csv("../data/raw/IPL.csv")

print(ipl.shape)

C:\Users\Om Mishra\AppData\Local\Temp\ipykernel_8376\2455846577.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  ipl = pd.read_csv("../data/raw/IPL.csv")

(283678, 65)

In [3]:
ipl.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
ipl.columns.tolist()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [5]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(35)
memory usage: 135.0+ MB

In [6]:
ipl[['batting_team', 'bowling_team']].head()

            batting_team                 bowling_team
0  Kolkata Knight Riders  Royal Challengers Bangalore
1  Kolkata Knight Riders  Royal Challengers Bangalore
2  Kolkata Knight Riders  Royal Challengers Bangalore
3  Kolkata Knight Riders  Royal Challengers Bangalore
4  Kolkata Knight Riders  Royal Challengers Bangalore

In [7]:
ipl[['match_id', 'date']].head()

   match_id        date
0    335982  2008-04-18
1    335982  2008-04-18
2    335982  2008-04-18
3    335982  2008-04-18
4    335982  2008-04-18

In [8]:
ipl['match_id'].nunique()

1193

In [9]:
ipl['innings'].value_counts().sort_index()

innings
1    146997
2    136510
3        83
4        76
5         8
6         4
Name: count, dtype: int64

In [10]:
sample_match = ipl['match_id'].iloc[0]

ipl[ipl['match_id'] == sample_match][
    ['match_id',
     'innings',
     'batting_team',
     'bowling_team',
     'runs_total',
     'wicket_kind']
].head(20)

,match_id,innings,batting_team,bowling_team,runs_total,wicket_kind
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,NaN
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,NaN
11,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,NaN
12,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
13,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
14,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
15,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,NaN
16,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,NaN
17,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,NaN
18,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,NaN
19,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,NaN

In [11]:
for col in ipl.columns:
    print(col)

Unnamed: 0
match_id
date
match_type
event_name
innings
batting_team
bowling_team
over
ball
ball_no
batter
bat_pos
runs_batter
balls_faced
bowler
valid_ball
runs_extras
runs_total
runs_bowler
runs_not_boundary
extra_type
non_striker
non_striker_pos
wicket_kind
player_out
fielders
runs_target
review_batter
team_reviewed
review_decision
umpire
umpires_call
player_of_match
match_won_by
win_outcome
toss_winner
toss_decision
venue
city
day
month
year
season
gender
team_type
superover_winner
result_type
method
balls_per_over
overs
event_match_no
stage
match_number
team_runs
team_balls
team_wicket
new_batter
power_surge_start
batter_runs
batter_balls
bowler_wicket
batting_partners
next_batter
striker_out

In [12]:
winner_cols = [col for col in ipl.columns if 'win' in col.lower()]
winner_cols

['win_outcome', 'toss_winner', 'superover_winner']

In [13]:
toss_cols = [col for col in ipl.columns if 'toss' in col.lower()]
toss_cols

['toss_winner', 'toss_decision']

In [14]:
ipl[['win_outcome']].drop_duplicates()

       win_outcome
0         140 runs
225        33 runs
473      9 wickets
692      5 wickets
1178     6 wickets
...            ...
240196    112 runs
247509    106 runs
272478    100 runs
276336     83 runs
276578    110 runs

[112 rows x 1 columns]

In [15]:
ipl[['toss_winner']].drop_duplicates().head(20)

                        toss_winner
0       Royal Challengers Bangalore
225             Chennai Super Kings
473                Rajasthan Royals
692                  Mumbai Indians
938                 Deccan Chargers
1178                Kings XI Punjab
2606          Kolkata Knight Riders
3041               Delhi Daredevils
42074          Kochi Tuskers Kerala
46042                 Pune Warriors
78545           Sunrisers Hyderabad
122920                Gujarat Lions
123649      Rising Pune Supergiants
136846       Rising Pune Supergiant
165702               Delhi Capitals
196800                 Punjab Kings
208771               Gujarat Titans
209507         Lucknow Super Giants
243817  Royal Challengers Bengaluru

In [16]:
ipl[['win_outcome', 'batting_team', 'bowling_team']].sample(20)

       win_outcome                 batting_team                 bowling_team
146289   7 wickets             Delhi Daredevils                Gujarat Lions
248562     29 runs               Mumbai Indians               Delhi Capitals
248386   6 wickets             Rajasthan Royals  Royal Challengers Bengaluru
126492   5 wickets              Kings XI Punjab          Sunrisers Hyderabad
212153   8 wickets          Sunrisers Hyderabad          Chennai Super Kings
58330      43 runs               Mumbai Indians  Royal Challengers Bangalore
82531    4 wickets          Chennai Super Kings        Kolkata Knight Riders
79790      41 runs               Mumbai Indians                Pune Warriors
19975      78 runs              Kings XI Punjab             Rajasthan Royals
107131   8 wickets          Chennai Super Kings  Royal Challengers Bangalore
17634    6 wickets              Deccan Chargers             Delhi Daredevils
151753     10 runs             Rajasthan Royals             Delhi Daredevils
231374   3 wickets               Gujarat Titans             Rajasthan Royals
67897    5 wickets        Kolkata Knight Riders          Chennai Super Kings
237857   7 wickets  Royal Challengers Bangalore               Delhi Capitals
144911     48 runs          Sunrisers Hyderabad        Kolkata Knight Riders
101832     32 runs              Kings XI Punjab  Royal Challengers Bangalore
278153      6 runs                 Punjab Kings  Royal Challengers Bengaluru
169636   8 wickets             Rajasthan Royals        Kolkata Knight Riders
197367  10 wickets             Rajasthan Royals  Royal Challengers Bangalore

In [17]:
[col for col in ipl.columns if 'team' in col.lower()]

['batting_team',
 'bowling_team',
 'team_reviewed',
 'team_type',
 'team_runs',
 'team_balls',
 'team_wicket']

In [18]:
[col for col in ipl.columns if 'winner' in col.lower()]

['toss_winner', 'superover_winner']

In [19]:
[col for col in ipl.columns if 'outcome' in col.lower()]

['win_outcome']

In [20]:
ipl[['team_reviewed']].drop_duplicates().head(20)

                      team_reviewed
0                               NaN
150472               Mumbai Indians
150735              Kings XI Punjab
151011  Royal Challengers Bangalore
151157        Kolkata Knight Riders
151263          Sunrisers Hyderabad
151379             Rajasthan Royals
152402             Delhi Daredevils
154373          Chennai Super Kings
166941               Delhi Capitals
195556                 Punjab Kings
208771               Gujarat Titans
208922         Lucknow Super Giants
244021  Royal Challengers Bengaluru

In [21]:
ipl[['team_type']].drop_duplicates()

  team_type
0      club

In [22]:
ipl[['team_runs', 'team_balls', 'team_wicket']].head(20)

    team_runs  team_balls  team_wicket
0           1           1            0
1           1           2            0
2           2           2            0
3           2           3            0
4           2           4            0
5           2           5            0
6           3           6            0
7           3           7            0
8           7           8            0
9          11           9            0
10         17          10            0
11         21          11            0
12         21          12            0
13         21          13            0
14         21          14            0
15         22          15            0
16         26          16            0
17         27          17            0
18         27          18            0
19         32          18            0

In [23]:
ipl.loc[:, ['match_id',
            'batting_team',
            'bowling_team',
            'team_runs',
            'team_balls',
            'team_wicket']].head(30)

,match_id,batting_team,bowling_team,team_runs,team_balls,team_wicket
0,335982,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,0
1,335982,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,0
2,335982,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,0
3,335982,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,0
4,335982,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,0
5,335982,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,0
6,335982,Kolkata Knight Riders,Royal Challengers Bangalore,3,6,0
7,335982,Kolkata Knight Riders,Royal Challengers Bangalore,3,7,0
8,335982,Kolkata Knight Riders,Royal Challengers Bangalore,7,8,0
9,335982,Kolkata Knight Riders,Royal Challengers Bangalore,11,9,0
10,335982,Kolkata Knight Riders,Royal Challengers Bangalore,17,10,0
11,335982,Kolkata Knight Riders,Royal Challengers Bangalore,21,11,0
12,335982,Kolkata Knight Riders,Royal Challengers Bangalore,21,12,0
13,335982,Kolkata Knight Riders,Royal Challengers Bangalore,21,13,0
14,335982,Kolkata Knight Riders,Royal Challengers Bangalore,21,14,0
15,335982,Kolkata Knight Riders,Royal Challengers Bangalore,22,15,0
16,335982,Kolkata Knight Riders,Royal Challengers Bangalore,26,16,0
17,335982,Kolkata Knight Riders,Royal Challengers Bangalore,27,17,0
18,335982,Kolkata Knight Riders,Royal Challengers Bangalore,27,18,0
19,335982,Kolkata Knight Riders,Royal Challengers Bangalore,32,18,0
20,335982,Kolkata Knight Riders,Royal Challengers Bangalore,38,19,0
21,335982,Kolkata Knight Riders,Royal Challengers Bangalore,39,20,0
22,335982,Kolkata Knight Riders,Royal Challengers Bangalore,43,21,0
23,335982,Kolkata Knight Riders,Royal Challengers Bangalore,43,22,0
24,335982,Kolkata Knight Riders,Royal Challengers Bangalore,44,23,0
25,335982,Kolkata Knight Riders,Royal Challengers Bangalore,50,24,0
26,335982,Kolkata Knight Riders,Royal Challengers Bangalore,54,25,0
27,335982,Kolkata Knight Riders,Royal Challengers Bangalore,55,26,0
28,335982,Kolkata Knight Riders,Royal Challengers Bangalore,59,27,0
29,335982,Kolkata Knight Riders,Royal Challengers Bangalore,59,28,0

In [24]:
pd.DataFrame({
    "column_name": ipl.columns
})

         column_name
0         Unnamed: 0
1           match_id
2               date
3         match_type
4         event_name
..               ...
60      batter_balls
61     bowler_wicket
62  batting_partners
63       next_batter
64       striker_out

[65 rows x 1 columns]

In [25]:
for i, col in enumerate(ipl.columns):
    print(i, col)

0 Unnamed: 0
1 match_id
2 date
3 match_type
4 event_name
5 innings
6 batting_team
7 bowling_team
8 over
9 ball
10 ball_no
11 batter
12 bat_pos
13 runs_batter
14 balls_faced
15 bowler
16 valid_ball
17 runs_extras
18 runs_total
19 runs_bowler
20 runs_not_boundary
21 extra_type
22 non_striker
23 non_striker_pos
24 wicket_kind
25 player_out
26 fielders
27 runs_target
28 review_batter
29 team_reviewed
30 review_decision
31 umpire
32 umpires_call
33 player_of_match
34 match_won_by
35 win_outcome
36 toss_winner
37 toss_decision
38 venue
39 city
40 day
41 month
42 year
43 season
44 gender
45 team_type
46 superover_winner
47 result_type
48 method
49 balls_per_over
50 overs
51 event_match_no
52 stage
53 match_number
54 team_runs
55 team_balls
56 team_wicket
57 new_batter
58 power_surge_start
59 batter_runs
60 batter_balls
61 bowler_wicket
62 batting_partners
63 next_batter
64 striker_out

In [26]:
interesting_cols = [
    col for col in ipl.columns
    if any(keyword in col.lower() for keyword in
           ['venue', 'ground', 'city', 'season',
            'winner', 'result', 'outcome',
            'match', 'toss', 'review'])
]

interesting_cols

['match_id',
 'match_type',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'season',
 'superover_winner',
 'result_type',
 'event_match_no',
 'match_number']

In [27]:
ipl[['match_won_by']].drop_duplicates().head(20)

                       match_won_by
0             Kolkata Knight Riders
225             Chennai Super Kings
473                Delhi Daredevils
692     Royal Challengers Bangalore
1178               Rajasthan Royals
2127                Kings XI Punjab
2839                Deccan Chargers
3536                 Mumbai Indians
15161                       Unknown
42537                 Pune Warriors
44442          Kochi Tuskers Kerala
76859           Sunrisers Hyderabad
122502      Rising Pune Supergiants
122920                Gujarat Lions
136846       Rising Pune Supergiant
165204               Delhi Capitals
194354                 Punjab Kings
208771               Gujarat Titans
209507         Lucknow Super Giants
245060  Royal Challengers Bengaluru

In [28]:
meta_cols = [
    'match_id',
    'season',
    'date',
    'venue',
    'city',
    'batting_team',
    'bowling_team',
    'toss_winner',
    'toss_decision',
    'match_won_by'
]

ipl[meta_cols].head()

,match_id,season,date,venue,city,batting_team,bowling_team,toss_winner,toss_decision,match_won_by
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders

In [29]:
match_summary = (
    ipl.groupby('match_id')
       .first()
       .reset_index()
)

print(match_summary.shape)

match_summary[
    [
        'match_id',
        'season',
        'date',
        'venue',
        'city',
        'toss_winner',
        'toss_decision',
        'match_won_by',
        'win_outcome'
    ]
].head()

(1193, 65)

,match_id,season,date,venue,city,toss_winner,toss_decision,match_won_by,win_outcome
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,140 runs
1,335983,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,33 runs
2,335984,2007/08,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,9 wickets
3,335985,2007/08,2008-04-20,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Royal Challengers Bangalore,5 wickets
4,335986,2007/08,2008-04-20,Eden Gardens,Kolkata,Deccan Chargers,bat,Kolkata Knight Riders,5 wickets

In [30]:
match_summary.to_csv(
    "../data/processed/match_summary.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

match_won_by
Mumbai Indians                 152
Chennai Super Kings            144
Kolkata Knight Riders          135
Rajasthan Royals               118
Royal Challengers Bangalore    114
Sunrisers Hyderabad             95
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  53
Gujarat Titans                  39
Punjab Kings                    38
Lucknow Super Giants            32
Deccan Chargers                 29
Unknown                         24
Royal Challengers Bengaluru     22
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64